### ISSUE TITLE
`komodo` missing from `sysinfo`

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#1029]
The current `komodo` version is supposedly added to the metadata (in `sysinfo`), however we don't see it in produced metadata.

fmu-dataio version: `2.9.2` and `2.9.3`

Example of `sysinfo` from live case (with fmu-dataio version `2.9.2`):
```yaml
tracklog:
  - datetime: "2025-02-25T08:19:27.574601Z"
    event: "created"
    user:
      id: ... # <redacted>
    sysinfo:
      fmu-dataio:
        version: "2.9.3"
      operating_system:
        hostname: ... # <redacted>
        operating_system: ... # <redacted>
        release: ... # <redacted>
        system: "Linux"
        version: "#1 SMP Fri Jan 10 05:56:06 EST 2025"
```

Reproduce:
- Run data export while sourcing Komodo
- Observe `komodo` not in the list of keys under `sysinfo` in the relevant `tracklog` events.

Expected behavior:
When running under Komodo, the current Komodo version is included in produced metadata.
