### ISSUE TITLE
Create and append to a manifest of exported data files

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-dataio#1055]
_Needs refinement_

FMU experiments have several start, running, and stop states possible: new experiment run, restart, rerun, failure, hook workflows, ...

It is useful in at least one context to keep a log of all exported files. A key use case is using this manifest to track whether or not a file has been uploaded to Sumo.

It could exist in a particular place on a realization basis, f.eks `share/results/.fmu_dataio_exported.json`. Or perhaps in the realization copy of `.fmu/`.

This file would contain a list of exported files with basic facts and subsections for other use cases, such as Sumo uploader. Taking one simple example, but as yaml

```yaml
- relative_path: share/results/.../somefile.roff
  absolute_path: /foo/.../realization-0/iter-0/share/results/.../somefile.roff
  exported_at: 1234-12-12T12:12:12.1234
  last_modified: 1234-12-12T12:12:12.1234  # if exported_at != last_modified, fail?
  user:
    ...  # Can an existing dataio model go here?
  sumo:
    case_id: <uuid4>
    object_id: <uuid4> | null
    uploaded: false
    uploaded_at: null
    ...
 ...
```

Related: https://github.com/equinor/fmu-sumo-uploader/issues/115
