### ISSUE TITLE
(Partly) standardize workflow names

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#133]
Consider to partly standardize workflow references. It is still an absolute requirements that each individual model can use local workflow names, but potentially parts of the definition could be standardized, e.g.

```
fmu:
  workflow:
    reference: "some name" <-- name that makes sense locally
    category: "structural modeling" <-- standardized name that can be used across, from whitelist.
```

(for discussion.)

The purpose of this is to enable logic to be built on top of this tag. In many cases this is the only tag that ensures uniqueness, but it is also currently completely non-standardized across assets.
