### ISSUE TITLE
Norwegian letters converted

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#226]
`global_variables.yml`:
```
  discovery:
    - short_identifier: Smørbukk
      uuid: ad214d87-8274-19da--REDACTED--
  field:
    - identifier: ÅSGARD
      uuid: ad214d87-8274-19da--REDACTED--
```

`metadata.yml`:
```
    - short_identifier: "Sm\xF8rbukk"
      uuid: ad214d87-8274-19da--REDACTED--
    field:
    - identifier: "\xC5SGARD"
      uuid: ad214d87-8274-19da--REDACTED--
```

Expected behavior: ÆØÅ carried through to metadata.
