### ISSUE TITLE
Content is not a string for seismic maps

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#260]
For seismic surfaces, `data.content` is exported as a dictionary, but must be a string to validate.

```
data:
  content:
    seismic:
      attribute: rms
      zrange: 12.0
      filter_size: -999.0
      scaling_factor: 1.0
```

Should be:
```
data:
  content: seismic
  seismic:
    attribute: rms
    zrange: 12.0
    filter_size: -999.0
    scaling_factor: 1.0
```
