### ISSUE TITLE
Access definitions

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#295]
It is expected that more granular access levels are required going forward. Access block currently:

```yaml
access:
  asset:
    name: Drogon
  ssdl: # proprietary ssdl stuff
    access_level: internal
    rep_include: true
```

Some potential user stories:
- As a data owner, I would like to limit general access to some key results while retaining general access to others, so that I can share non-sensitive data only from a specific case
- As a data owner, I would like to exclude specific data objects from specific access groups, to avoid confusion and misunderstandings

A suggestion for an updated access block could be:
```yaml
access:
  asset:
    name: Drogon
  roles:
    asset: true # always "true" so reduntant?
    license_partner: true
    internal: false
  ssdl: # proprietary ssdl stuff
    access_level: internal
    rep_include: true
```

This introduces the ` access.roles` which can be expanded on.

Corresponding arguments must be made available in fmu-dataio. Sensible defaults should be set in fmu-dataio (related: #238). It must be intuitive to the end user what accesses he is granting while exporting.

**Comment by perolavsvendsen** [comment]
Refined to:

Support classifying each outgoing data object as either `internal` or `restricted`. Suggested API is:

```python
from fmu.dataio import ExportData

exp = ExportData(
    content="inplace",
    name="MyName",
    ssdl={"access_level: "asset", "rep_include": False} # <-- currently implemented, subject to deprecation
    access_level="restricted" # <-- proposed new implementation
)
```

...producing metadata that looks like:

```yaml
access:
  asset:
    name: MyAsset
  ssdl:
    access_level: "asset" # SSDL/REP - deprecate?
    rep_include: False    # SSDL/REP - deprecate?
  classification: "restricted" # <-- NEW!
```

- [ ] Direct input takes precedence. Second priority is defaults in `global_variables.yml`. Last fall back is default `restricted` set in fmu-dataio.
- [ ] Add to schema, not required for now.
