### ISSUE TITLE
Add content: Well paths

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#318]
[Placeholder, to be refined]

- Export (simulated) well paths - well paths of wells being made/modified during FMU runs

- [ ] Format
- [ ] Use case examples
- [ ] Definitions, metadata
- [ ] Implementation in fmu-dataio

**Comment by perolavsvendsen** [comment]
Discussions 13/12-2023 @jcrivenaes @HansKallekleiv 

- There are endpoints on SSDL that can offer well paths and logs. However, no guarantee that these logs match those used in FMU.
- Operations can (will) happen to paths and logs before/during FMU runs.

Consider doing this:
---- Iteration 0 ----
- [ ] Design/make export functionality for paths/logs to be inserted into FMU
- [ ] Export wells/logs out of FMU, upload to Sumo, consume in Webviz

Options:
- Export single object, split to multiple objects prior to upload
- Export single object, upload single object, consume single object
- Export multiple objects, upload/consume multiple objects

Well paths:
```yaml
class: well_path??
data:
  name: <name as in RMS etc>
  content: well_path
  well_path:
    logrun: XX
    datum: msl
```

Well logs:
```yaml
class: well_log??
data:
  name: <name as in RMS etc>
  content: well_log
  well_log:
    logrun: XX
    datum: msl
    discrete: True
    discrete_codes:
      1: ValueThree
      2: ValueTwo
```

OR export as one table path + logs? `xtgeo.well.Well`-object contains:
- Path
- All logs as table

As one object:
```yaml
data:
  content: well
  well:
    logrun: XX
    datum: msl
    logs:
      MyLog:
        discrete: True
        discrete_codes:
          1: ValueThree
          2: ValueTwo
      MyOtherLog:
        discrete: True
        discrete_codes:
          1: ValueThree
          2: ValueTwo
```

---- Iteration 1 ----
- [ ] Reduce size of exported data (e.g. concatenate discrete logs)
- [ ] Add links to masterdata. Option to just use `data.name` as for stratigraphic objects? Can `data.name` be linked to `uwi` (well name as a string, Universal Well ID)

Ever-returning discussion: What about masterdata (for wells) in FMU?

Translation, as for stratigraphic column?
"12/2-7":
  "smda": <uuid4>
