### ISSUE TITLE
Support for blocked /modelled well logs

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/fmu-dataio#372]
- Relates to https://github.com/equinor/webviz/issues/365

Implementation will require some discussion.

- As table?
- Linked to `well_uuid` from masterdata if applicable.
- Include md/tvd (downsample as raw log?)
- Include modelling logs? (RMS calculated/modified logs used as input)

**Comment by perolavsvendsen** [comment]
https://github.com/equinor/webviz/issues/365

**Comment by perolavsvendsen** [comment]
Discussion 4 oct 2023:
- In XTgeo, blocked log looks and behaves as any well log.
- Should be possible to export logs out on `csv` format
- As-is is that no logs are exported/stored to Sumo
- Logs from existing wells can be fetched from other sources. However, sampled logs from e.g. planned wells are not available outside FMU. This is considered a prediction created by FMU.

Format?
XTgeo uses `xyz` (`csv`) format

Should FMU metadata for wells be synched with current standards in SMDA?
Probably need to have a record of `uuid`s in SMDA in FMU, so that we can connect the two in outgoing metadata. Similar to links to stratigraphic column. Will RMS support lineage, so that these things can follow the data on input and be accessible when exporting back out?

Starting point:
Export (blocked) wells out of FMU, populate with metadata, store in Sumo.
  - Dataframe with specific columns (`csv` formatted)
  - Dictionaries/legend for values in the table can be inserted into metadata
  - Simplest now; 1 file per well, containing both well path and (all) well logs
Export per realization first, but figure out if should be exported as pre-processed (case wide) data
  - For situations where these wells are not found elsewhere, i.e. they have been modified on input to FMU model.

```yaml
class: table
data:
  content: well # /(blocked_well)
  well:
    logs:
      - name: MyLog
        type: continuous
      - name: MyOtherLog
        type: discrete
    path:
     xx: yy
fmu:
  grid_model:
    xx
```

Wait:
- SMDA/masterdata references

@jcrivenaes @HansKallekleiv
