### ISSUE TITLE
Handle empty entries in the stratigraphy list

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#383]
If user puts empty entries in the stratigraphy in `global_variables`, e.g.:

```yaml
MyFormation:
  stratigraphic: True
  name: My Fm. Top
  alias:
    - MyFormation
    - OtherAlias
    -                   # <-- PROBLEM!
  stratigraphic_alias:
    - Some GP. Top
    - SomeOther GP. Base   
    -                   # <-- PROBLEM!
```

---> This will currently export with `null` in outgoing metadata. In validation, it is expected to be `string` hence not validated. Tricky to debug. `fmu-dataio` should catch this and either warn or ignore or both.

_Originally posted by @perolavsvendsen in https://github.com/equinor/fmu-dataio/issues/373#issuecomment-1782763705_

Suggested solution:
- fmu-dataio gives warning when empty entries are detected, then ignores them
