### ISSUE TITLE
Improved status sharing between ERT and SUMO

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-dataio#391]
- **Number of realizations.**
  - Today SUMO assumes number of realizations based on max. real number found. 
  - ERT can easily add a new environment variable stating number of realizations, and expose this in the same pre-ensemble workflow that `fmu-dataio` is using today for registering an interation/enmseble.
- **Status**

**Comment by perolavsvendsen** [comment]
I also learned this yesterday. I guess it would be relatively easy to implement expected realizations into the `case` object in the metadata, e.g.

```yaml
fmu:
  case:
    name: MyCase
    uuid: <uuid4>
    expected_realizations: 39
```

Not thought through, so don't implement this directly 😬. But as a concept, I think it should work.
