### ISSUE TITLE
Collection of issues wrt Snorre work spring 2024

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#497]
A kind of epic collection; note there may be overlap in other issues

- [ ] ECLGRID2ROFF miss metadata - see https://github.com/equinor/subscript/issues/678
- [ ] Output from GRID3D_AVERAGE_MAP does not include grid, and file name may overlap
- [ ] Order of dates in file names is not reverted, even when the user applied the classmethod setting (bug)
- [ ] Missing metadata on seismic cube; this also includes possible missing tags
- [ ] Horizons, have more metadata on origin of surfaces (see point 12 below)
- [ ] Various missing tags of metadata (cf. 13, 14 in list below)

This is based on this edited list (in Norwegian):

```
4.	Mangler funksjon i xtgeo for  metadata på eclipse roff filer (ert forward modell ECLGRID2ROFF)  - DATAIO
5.	Hvordan gjøre det med output filnavn i forward modell GRID3D_AVERAGE_MAP, når en har flere varianter av f.eks average_poro.gri kart (fra geo, eclipse, pemgrid).  Kan vi ha samme filnavn, men ulik id? Mangler tag for metadata som angir hvilket grid det beregnes fra. - XTGEO
6.	Issue i xtgeo med rekkefølge av datoer i filnavn,  snur rekkefølge til monitor-base i noen workflows. Metadata blir imidlertid OK, men forvirrende for bruker. - DATAIO
8.	4D attr kart: Mangler tag i metadata for navn på seismisk kube  - DATAIO
9.	4D attr kart: Mangler tag i metadata for navn på flater, en eller to flater.  + eventuell offset  - DATAIO
10.	4d cubes export- mangler tag i metadata for link til original navn på obs kuber  - DATAIO
11.	Obs 4D single cubes: Få tak i snorre single kubes for alle 4D innsamlingsdatoer. (har bare  funnet et par kuber; 1997 og 2006) som brukes nå, som et eksempel. (For å lage diff on the fly) - ?
12.	Horizons export: skulle vi hatt en tag i metadata som sier hvilken versjon («ds_extracted_geogrid», «depthsurface_prostprocessed»++) som er eksportert, evt noe mer som gir info om flaten? - DATAIO
13.	Horizon export: skulle vi hatt en tag i metadata som sier om flaten er erodert eller ikke? - DATAIO
14.	Grid export:       skulle vi hatt en tag i metadata som sier om griddet er erodert eller ikke? – DATAIO
```

**Comment by perolavsvendsen** [comment]
> 12.	Horizons export: skulle vi hatt en tag i metadata som sier hvilken versjon («ds_extracted_geogrid», «depthsurface_prostprocessed»++) som er eksportert, evt noe mer som gir info om flaten? - DATAIO

`tagname` is used for this.

Real examples:

JC:
```yaml
data:
  name: "Stoe 4 JC"
  stratigraphic: true
  alias:
    - "TopStoe4"
  content: "depth"
  tagname: "DS_extracted_gf_run2" <--
  format: "irap_binary"
  layout: "regular"
  unit: "m"`
```

JS:
```yaml
data:
  name: "Eiriksson Fm. 2 JS Top"
  stratigraphic: true
  alias:
    - "Eiriksson_Fm_2_Top"
  content: "depth"
  tagname: "depth_structural_model" <--
  format: "irap_binary"
  layout: "regular"
  unit: "m"
```
