### ISSUE TITLE
Add value range metadata for 3D grids

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-dataio#530]
We currently only need "global value range". Should use a metadata namespace which makes it possible to later also add something non-global, like e.g. "subzone" value range.

E.g. 
```yaml
valuerange:
   global:
       min:
       max:
```
