### ISSUE TITLE
Allow user to override Access.classification

### ISSUE THREAD

**Issue by janbjorge** [equinor/fmu-dataio#540]

**Comment by perolavsvendsen** [comment]
This needs more context, but it is a fundamental requirement that the user can use the `classification` argument to the `.export()` method, and that this works.

**Comment by tnatt** [comment]
More context 😃  
The pydantic model `global_configuration.Access` has a bit of limitations.

- `ssdl.access_level` is  required.
- `classification` is mirrored from the `ssdl.access_level,` and users can't have a classification key in their global config to set this value

So this won't work:
```
access:
  classification: "internal"
```
It will complain about a missing access_level and not produce metadata
And this will set the classification to "internal"
```
access:
  ssdl:
    access_level: "internal" 
    rep_include: True
  classification: "restricted"
```
