### ISSUE TITLE
Make tracklog definition explicit

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#548]
`tracklog` is currently a list of events. On initialization, fmu-dataio will create the first entry, which will have `event: created`.

For various reasons, it may be better to be explicit on the events and make `tracklog` (or some new attribute?) an object instead. Example:

```yaml
tracklog:
  created: # single 
    datetime: ...
    user: ...
    sysinfo: ...
  updated: # list of events
    - [Event]
    - [Event]
  archived: ... # single
  deleted: ... # single
```

- Enable explicit indexing of `tracklog.created` but not necessarily all sub-attributes of it - and not necessarily all the later updates to a case. Currently: `$contractual` contains the whole `tracklog`, implying indexing of all of it.

We can consider renaming to something else (e.g. "events" or similar) to implement new while deprecating `tracklog` to make this change graceful (changing `tracklog` from list to object will probably be painful.)

- [ ] Refine this further, and agree on the stories to solve with the tracklog

Related issue:
https://github.com/equinor/fmu-dataio/issues/12
