### ISSUE TITLE
Simplify implementation of fmu.context

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#592]
Based on discussions 10/4-2024 @tnatt @jcrivenaes @HansKallekleiv 

Current implementation/handling of `context` is cumbersome, and somewhat complicated (for many reasons).

Related issues/tasks:
- [ ] #588
- [x] #544 
- [ ] #293
- [ ] https://github.com/equinor/fmu-dataio/issues/408#issuecomment-1889426535
- [x] #593 
- [ ]  #615

## The FMU block of the metadata
_These are the principles_

```yaml
fmu:
  model: ... # always present
  case: ...  # always present
  iteration: ... # present if data belongs to an iteration/ensemble
  realization: ... # present if data belongs to a realization

  (aggregation: ... # present if data represents an aggregation)
```
There is implicit logic embedded in this, e.g. "if `iteration` and not `realization` then _data is on iteration level_". However, embedding such logic in all consumers would be cumbersome. Therefore, we mirror this logic in `fmu.context`:

```yaml
  context: ...
```

## Suggested tasks
- [ ] Enum allowed input to "context"
- [ ] Remove use of "context" for handling "preprocessed" or "symlink" logic
- [ ] Set context primarily based on detected context, rather than given context (goal: Generally not needed as an argument)
