### ISSUE TITLE
Required property data.spec missing from produced metadata

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#650]
When testing `2.2.0.b2`, fmu-dataio is producing metadata without the required parameter `data.spec`. This causes produced metadata to not validate against the schema.

`data` block in produced metadata:
```yaml
data:
  content: depth
  alias:
  - Halibut_Bank_Fm_Top
  bbox:
    xmin: 454895.238842204
    xmax: 494304.7611306861
    ymin: 6500673.490122103
    ymax: 6541426.51171875
  description:
  - Depth surface extracted from structural model
  format: irap_binary
  is_observation: false
  is_prediction: true
  layout: regular
  name: Turbot Bank Fm. 1 JS Top
  offset: 0.0
  stratigraphic: true
  tagname: depth_structural_model
  undef_is_zero: false
  unit: m
  vertical_domain: depth
  depth_reference: msl

```

`sysinfo`:
```yaml
  sysinfo:
    fmu-dataio:
      version: 2.2.0b2
    operating_system:
      hostname: st-rsv17-17-12.st.statoil.no
      operating_system: Linux-3.10.0-1160.114.2.el7.x86_64-x86_64-with-glibc2.2.5
      release: 3.10.0-1160.114.2.el7.x86_64
      system: Linux
      version: '#1 SMP Sun Mar 3 08:18:39 EST 2024'
```

Ref: https://github.com/equinor/fmu-dataio/blob/9a08f4e2fa8af6db211a334384b2fd958d6f19fb/tests/test_schema/test_pydantic_logic.py#L339
