### ISSUE TITLE
Include `_ERT_EXPERIMENT_ID` in case metadata

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#670]
`_ERT_EXPERIMENT_ID` is exposed as an environment variable ref this table from #605

| ERT mode | On client | On Compute node |
|--|--|--|
| workflow | `_ERT_EXPERIMENT_ID`<br> `_ERT_ENSEMBLE_ID`<br> `_ERT_SIMULATION_MODE` | N/A |
| test-run (forward model) | `_ERT_EXPERIMENT_ID`<br> `_ERT_ENSEMBLE_ID`<br> `_ERT_SIMULATION_MODE` <br><br>`_ERT_RUNPATH`<br> `_ERT_ITERATION_NUMBER`<br> `_ERT_REALIZATION_NUMBER` | N/A |
| ensemble experiment (forward model) | N/A | `_ERT_RUNPATH`<br> `_ERT_ITERATION_NUMBER`<br> `_ERT_REALIZATION_NUMBER` |

We should include this in the outgoing _case_ metadata, to learn more about the likeliness between `experiment` and `case`

In the metadata, suggest we put this into a separate block:

```yaml
data:
  ...
fmu:
  case:
    name: ...
    uuid: ...
  ert:
    experiment:
      id: <_ERT_EXPERIMENT_ID>  # if it is a uuid, use "uuid"
```
