### ISSUE TITLE
Consider making parameters objects

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#79]
Currently, `parameters` are key:value pairs. To prepare for future possible expansions, consider making this into an object, e.g.

```
parameters:
  SENSNAME:
    value: VALUE
    description: MyDescription
```
