### ISSUE TITLE
ENH: Consider (!) dedicated link to stratigraphic column

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#851]
Currently, each data object which represents a stratigraphic entity (horizon, zone) is linked to the stratigraphic column via `data.name`. Since the "name" of an object within FMU can be completely arbitrary, we use a lookup function which matches "FMU-name" with "Official name", and replaces. In the stratigraphic column, then name is the identifier.

Example:

In global_variables:
```yaml
stratigraphy:
  Viking_Top:
    name: VIKING Gp. Top
```

When exporting e.g. a surface representing "Viking Top", the name will initially be "Viking_Top". We do a lookup in `stratigraphy`, and if "Viking_Top" is found, we replace the name with the official one. Resulting metadata looks like this:

```yaml
data:
  name: VIKING Gp. Top
  stratigraphic: true
```

Similarly, if we export "Some Other Name" which is NOT in the stratigraphy dictionary, resulting metadata becomes:
```yaml
data:
  name:  Some Other Name
  stratigraphic: false
```

Meanwhile, other references to master data sits in the `masterdata` block, e.g.

```yaml
masterdata:
  smda:
    field: ...
    stratigraphic_column: ...
```

# Suggestion for discussion
Instead of using `data.name` as the identifier, we use an explicit one. I.e. we create something like:

```yaml
masterdata:
  smda:
    stratigraphic_column: <uuid4> # id of the strat column in SMDA
    stratigraphic_entity:
      identifier: <Name of the Horizon> # 🆕
```

This may be easier to both understand and use further. It is not a great pattern than we have a bool ("stratigraphic") which determines if `data.name` is an actual identifier, or just a string.
