### ISSUE TITLE
data.smda_entity input is not checked against alias list

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-dataio#853]
Currently the only time `fmu-dataio` will convert `data.name` to the stratigraphic name is if the `name` input is defined as key in the `stratigraphy` block in the config. Should it not also check if the name is within any alias list, and then do the conversion? What is the purpose of the alias list if not? It is added as metadata, but it doesn't seem very usable in the current state.

e.g.

``` yaml
stratigraphy:
  TopVolantis:
    stratigraphic: true
    name: VOLANTIS GP. Top
    alias:
    - TopVOLANTIS
    - TOP_VOLANTIS
```

and exporting a surface with `name="TopVOLANTIS"` will produce metdata with `data.name="TopVOLANTIS"` and `stratigraphic=False` but should rather be `data.name="VOLANTIS GP. Top"` and `stratigraphic=True`
