### ISSUE TITLE
Create a minimal definition for the `product` key in metadata

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-dataio#876]
This key should be what differentiates data as a standard result data product, such that we can filter flexible exports with standardized exports. A minimal product key could look something like this, to be added onto later.

```yml
product:
  type/name: inplace_volumes
  # result_schema: URL to inplace_volumes.json?
```

These fields are subject to further discussion/refinement. This key should only be present when data is exported with a simplified function. It is a "stamp" of data quality.
