### ISSUE TITLE
Inplace_volumes

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#927]
## User story
As a consumer of `FMU Initial Inplace Volumes`, I would like to know the relative order of the ZONE values, so that I can display them correctly.

## Background/description
Inplace volumes are exported as CSV-formatted tables, where `ZONE` is a standard (index) column. The values `ZONE` correspond to the zones in the grid from which the volumes were calculated. However, no information is currently included on the relative sorting of these values. The (normally) correct way to sort these is stratigraphic, from youngest to oldest.

(Other possible sortings are also used, e.g. by volume value.)

A possible mitigation of this would be to get and include the relative order of ZONE values in the outgoing metadata so that consumers can use that as a guide for sorting the tables when displaying.

## Tasks
- [ ] Investigate if we can actually know the internal stratigraphic order (do they appear stratigraphically sorted from the RMS volumetrics job?) (Assumption is that they do.)
- [ ] Get the internal sorting, and include it in metadata.

## Suggested metadata structure
This is highly related to the larger topic of "internal master data". However, as a step on the way, perhaps do this as part of the specific metadata structure for inplace volumes, e.g.:

```yaml
# consider this as pseudo-code, may not reflect the actual implementation
data:
  product:
    name: inplace_volumes
  content: inplace_volumes
  inplace_volumes:
    zones: # sorted dictionary, i.e. enumerating it gives sort order
      - name: MyZoneA
        smda:
          identifier: My Zone. A # if in the stratigraphic column
      - name: MyZoneB
        smda:
          identifier: My Zone. A # if in the stratigraphic column
```

There are many other, possibly better, implementations of this. The above included as one example, for discussion.

## Requirements
- [ ] Can be sustainably and consistently produced
- [ ] Positive or negligible negative influence on user experience
- [ ] Positive or negligible negative influence on robustness & changeability

## Feedback
- [ ] Webviz

## FMU results epic
- [ ] https://github.com/equinor/fmu-results-activities/issues/3

## Related
- [ ] https://github.com/equinor/webviz/issues/728
